language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: BSDPEZ3oBNJ+FxmRxXF2qPpOC3RUQTNAJ0xpDCczrZt1eJNlyPOUV+kmY8CbBvo2LkjFkX2gO5hO/924SPJo7ZBKOdN+K8ngNjk2mjkRtXqslweEBkZqj9w28vGQR3EshhGVmKkH50WAerl3yZ2KifnL420VGToUw9zvE2mEuDU=
  - secure: Gw1FYoSXqxdQ/fJDI2+ozw+K7cQ1qZviW6ujecQsv1yzh0TIpPAkqZSZJ/o+Im4Osob4s+dQF4lj0R2+JVtomXeLkJslZjq/qjzaZ9unDeRmfE24Z3IoQICjd8hfHnyaFo/4+++tgtHRynfBX8DOmoF/+EBYK+TnJ2jp/NdHIoA=
